# Setup & Import File

In [5]:
#直接執行以下程式
import pandas as pd

# 1. 定義檔案 ID (助教提供的 garments_worker_productivity.csv)
file_id = '16lYjDveb2tkQ8X2Idf3s-ytjXhGbeAGp'
url = f'https://drive.google.com/uc?id={file_id}'

# 2. 讀取資料 (確保這一行左邊完全沒有空格)
data = pd.read_csv(url)

# 3. 顯示前五筆資料
display(data.head())

,date,quarter,department,day,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,actual_productivity
0,1/1/2015,Quarter1,sweing,Thursday,8,0.80,26.16,1108.0,7080,98,0.0,0,0,59.0,0.940725
1,1/1/2015,Quarter1,finishing,Thursday,1,0.75,3.94,NaN,960,0,0.0,0,0,8.0,0.886500
2,1/1/2015,Quarter1,sweing,Thursday,11,0.80,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570
3,1/1/2015,Quarter1,sweing,Thursday,12,0.80,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570
4,1/1/2015,Quarter1,sweing,Thursday,6,0.80,25.90,1170.0,1920,50,0.0,0,0,56.0,0.800382

# Question 1

In [6]:
# Show the datatype of every columns.
print("--- Q1: 資料類型 ---")
data.info()

--- Q1: 資料類型 ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   1197 non-null   object
 1   quarter                1197 non-null   object
 2   department             1197 non-null   object
 3   day                    1197 non-null   object
 4   team                   1197 non-null   int64
 5   targeted_productivity  1197 non-null   float64
 6   smv                    1197 non-null   float64
 7   wip                    691 non-null    float64
 8   over_time              1197 non-null   int64
 9   incentive              1197 non-null   int64
 10  idle_time              1197 non-null   float64
 11  idle_men               1197 non-null   int64
 12  no_of_style_change     1197 non-null   int64
 13  no_of_workers          1197 non-null   float64
 14  actual_productivity    1197 non-null   float64
dtypes: float64(6), int64(5), object(4)
memory usage: 140.4+ KB

# Question 2

In [7]:
# Check each row for the number of NaN cells and show the column name and corresponding number. After that fill in the missing values in the 'wip' column with 0.
print("--- Q2: 填補缺失值 ---")
print("填補前缺失值數量：\n", data.isnull().sum())

data['wip'] = data['wip'].fillna(0)

print("\n填補後缺失值數量：\n", data.isnull().sum())

--- Q2: 填補缺失值 ---
填補前缺失值數量：
 date                       0
quarter                    0
department                 0
day                        0
team                       0
targeted_productivity      0
smv                        0
wip                      506
over_time                  0
incentive                  0
idle_time                  0
idle_men                   0
no_of_style_change         0
no_of_workers              0
actual_productivity        0
dtype: int64

填補後缺失值數量：
 date                     0
quarter                  0
department               0
day                      0
team                     0
targeted_productivity    0
smv                      0
wip                      0
over_time                0
incentive                0
idle_time                0
idle_men                 0
no_of_style_change       0
no_of_workers            0
actual_productivity      0
dtype: int64

# Question 3

In [8]:
# Mean and median of targeted productivity.
mean_val = data['targeted_productivity'].mean()
median_val = data['targeted_productivity'].median()

print("--- Q3: targeted_productivity 統計 ---")
print(f"Mean = {mean_val}")
print(f"Median = {median_val}")

--- Q3: targeted_productivity 統計 ---
Mean = 0.7296324143692565
Median = 0.75

# Question 4

In [9]:
# Find the correlation of team, idle time, no of workers, and targeted productivity.
cols = ['team', 'idle_time', 'no_of_workers', 'targeted_productivity']
corr_matrix = data[cols].corr()

display(corr_matrix)

,team,idle_time,no_of_workers,targeted_productivity
team,1.000000,0.003796,-0.075113,0.030274
idle_time,0.003796,1.000000,0.058049,-0.056181
no_of_workers,-0.075113,0.058049,1.000000,-0.084288
targeted_productivity,0.030274,-0.056181,-0.084288,1.000000

# Question 5

In [10]:
# Save the standardized 'actual_productivity' values to a new column, 'Z_actual', and then display the first and last 5 rows after removing 'targeted_productivity'.
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data['Z_actual'] = scaler.fit_transform(data[['actual_productivity']])
data = data.drop(columns=['targeted_productivity'], errors='ignore')
display(data)

,date,quarter,department,day,team,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,actual_productivity,Z_actual
0,1/1/2015,Quarter1,sweing,Thursday,8,26.16,1108.0,7080,98,0.0,0,0,59.0,0.940725,1.178994
1,1/1/2015,Quarter1,finishing,Thursday,1,3.94,0.0,960,0,0.0,0,0,8.0,0.886500,0.868096
2,1/1/2015,Quarter1,sweing,Thursday,11,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570,0.375423
3,1/1/2015,Quarter1,sweing,Thursday,12,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570,0.375423
4,1/1/2015,Quarter1,sweing,Thursday,6,25.90,1170.0,1920,50,0.0,0,0,56.0,0.800382,0.374342
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1192,3/11/2015,Quarter2,finishing,Wednesday,10,2.90,0.0,960,0,0.0,0,0,8.0,0.628333,-0.612090
1193,3/11/2015,Quarter2,finishing,Wednesday,8,3.90,0.0,960,0,0.0,0,0,8.0,0.625625,-0.627619
1194,3/11/2015,Quarter2,finishing,Wednesday,7,3.90,0.0,960,0,0.0,0,0,8.0,0.625625,-0.627619
1195,3/11/2015,Quarter2,finishing,Wednesday,9,2.90,0.0,1800,0,0.0,0,0,15.0,0.505889,-1.314120
1196,3/11/2015,Quarter2,finishing,Wednesday,6,2.90,0.0,720,0,0.0,0,0,6.0,0.394722,-1.951489

# Question 6

In [11]:
# 將smv分成不同的區間，分別是'0-10', '11-20', '21-30', '31-40', '41-50', '50+'，然後將每一列對應的區間列出
bins = [0, 10, 20, 30, 40, 50, float('inf')]
labels = ['0-10', '11-20', '21-30', '31-40', '41-50', '50+']
data['smv_group'] = pd.cut(data['smv'], bins=bins, labels=labels, include_lowest=True)
display(data[['smv', 'smv_group']])

        smv smv_group
0     26.16     21-30
1      3.94      0-10
2     11.41     11-20
3     11.41     11-20
4     25.90     21-30
...     ...       ...
1192   2.90      0-10
1193   3.90      0-10
1194   3.90      0-10
1195   2.90      0-10
1196   2.90      0-10

[1197 rows x 2 columns]

# Question 7

In [12]:
# 將'quarter'column 進行季度映射，使用{'Quarter1': 1, 'Quarter2': 2, 'Quarter3': 3, 'Quarter4': 4, 'Quarter5': 5}進行標籤編碼，並将結果儲存到新column'quarter_encoded'中。
quarter_map = {
    'Quarter1': 1,
    'Quarter2': 2,
    'Quarter3': 3,
    'Quarter4': 4,
    'Quarter5': 5
}
data['quarter_encoded'] = data['quarter'].map(quarter_map).astype(float)
display(data)

,date,quarter,department,day,team,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,actual_productivity,Z_actual,smv_group,quarter_encoded
0,1/1/2015,Quarter1,sweing,Thursday,8,26.16,1108.0,7080,98,0.0,0,0,59.0,0.940725,1.178994,21-30,1.0
1,1/1/2015,Quarter1,finishing,Thursday,1,3.94,0.0,960,0,0.0,0,0,8.0,0.886500,0.868096,0-10,1.0
2,1/1/2015,Quarter1,sweing,Thursday,11,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570,0.375423,11-20,1.0
3,1/1/2015,Quarter1,sweing,Thursday,12,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570,0.375423,11-20,1.0
4,1/1/2015,Quarter1,sweing,Thursday,6,25.90,1170.0,1920,50,0.0,0,0,56.0,0.800382,0.374342,21-30,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1192,3/11/2015,Quarter2,finishing,Wednesday,10,2.90,0.0,960,0,0.0,0,0,8.0,0.628333,-0.612090,0-10,2.0
1193,3/11/2015,Quarter2,finishing,Wednesday,8,3.90,0.0,960,0,0.0,0,0,8.0,0.625625,-0.627619,0-10,2.0
1194,3/11/2015,Quarter2,finishing,Wednesday,7,3.90,0.0,960,0,0.0,0,0,8.0,0.625625,-0.627619,0-10,2.0
1195,3/11/2015,Quarter2,finishing,Wednesday,9,2.90,0.0,1800,0,0.0,0,0,15.0,0.505889,-1.314120,0-10,2.0
1196,3/11/2015,Quarter2,finishing,Wednesday,6,2.90,0.0,720,0,0.0,0,0,6.0,0.394722,-1.951489,0-10,2.0

# Question 8

In [13]:
# Export csv
filename = '112034038_林彥妤.csv'
data.to_csv(filename, index=False)

print(f"--- Q8: {filename} ---")

--- Q8: 112034038_林彥妤.csv ---